name = "multi-worker"
main = "src/index.js"
compatibility_date = "2024-12-05"

[vars]
METRICS_URL = "metrics.com/my-metrics"

[[subworkers]]
name = "WORKER_B"
class = "WorkerB"

[[subworkers]]
name = "WORKER_C"
main = "src/workerC.js"
