name = "multi-entrypoint"

# any files that define a worker either as default export
# or as class exported that implements WorkerEntrypoint interface
entrypoints = ["src/index.js", "src/workerC.js"]

compatibility_date = "2024-12-05"

[vars]
METRICS_URL = "metrics.com/my-metrics"
